#!/usr/bin/env sh

# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# yabai setting options
yabai -m config external_bar               all:35:0
yabai -m config window_border              on
yabai -m config window_border_width        2
yabai -m config active_window_border_color 0xffe0a316
yabai -m config normal_window_border_color 0xffe0a316
yabai -m config window_border_radius       2
yabai -m config window_opacity            on 

# Space padding
yabai -m config top_padding                6
yabai -m config bottom_padding             4
yabai -m config left_padding               4
yabai -m config right_padding              4
yabai -m config layout                     bsp
yabai -m config window_gap                 05
yabai -m config window_placement           second_child 
yabai -m config window_zoom_persist        on
yabai -m config window_topmost             off
yabai -m config window_shadow              on
yabai -m config active_window_opacity      1.0 
yabai -m config normal_window_opacity      0.30 
yabai -m config window_border_hidpi        on
yabai -m config window_border_blur         off 

# Window splitting
yabai -m config split_ratio                0.50
yabai -m config split_type                 auto
yabai -m config auto_balance               off 
yabai -m config

# Mouse controls
yabai -m config mouse_modifier             fn
yabai -m config mouse_action1              move
yabai -m config mouse_action2              resize 
yabai -m config mouse_drop_action          swap


echo "yabai configuration loaded.."
